config/routes.rb
Rails.application.routes.draw do
  resources :addresses do
    collection do 
      get "state"
    end
  end
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/stimulus", to: "stimulus#index"
  get "/preview", to: "stimulus#preview_stimulus"
  get "/messages", to: "stimulus#messages"

  # Defines the root path route ("/")
  root "posts#index"
  get "/live_search", to: "cocktails#index"
  get "/all_get_data", to: "cocktails#get_data"
 
  get "/request_post", to: "requests/request#index"
  get "/request", to: "requests/request#new"
  post "/request", to: "requests/request#create"
  
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: name
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("posts", partial: "posts/post", locals: { post: @post})
        end
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.turbo_stream do
        render turbo_stream: turbo_stream.update(@post, partial: "posts/post", locals: { post: @post })  
        end
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(@post)
      end      
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
    <p>
        <strong>Title:</strong>
        <%= post.title %>
    </p>

    <p>
        <strong>Body:</strong>
        <%= post.body %>
    </p>

    <p>
        <%= link_to "Show this post", post, data: { turbo_frame: "modal" } %>
    </p>

    <p>
        <%= link_to "Edit this post", edit_post_path(post), data: { turbo_frame: "modal" } %>
        <%= button_to "Destroy this post", post_path(post), method: :delete %>
    </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= turbo_frame_tag :modal do %>
    <div data-controller="turbomodl" data-action="turbo:submit-end->turbomodl#submitEnd">
      <%= render "form", post: @post %>
    </div>

    <br>

       

    <% end %>

app/views/posts/index.html.erb
<%= link_to "Stimulus", "/stimulus" %>
<br/>
<%= link_to "Address", addresses_path %>
<br/>
<%= link_to "Live Search", "/live_search" %>
<br/>
<%= link_to "Requests JS", "/request_post" %>
<p style="color: green"><%= notice %></p>

    <h1>Posts</h1>
    <div id="posts">
        <% @posts.each do |post| %>
            <%= render post %>
        <% end %>
    </div>

<%= link_to "New post", new_post_path, data: { turbo_frame: "modal"}  %>

app/views/posts/new.html.erb
<%= turbo_frame_tag :modal do %>
    <div data-controller="turbomodl" data-action="turbo:submit-end->turbomodl#submitEnd">
        <h1>New post</h1>

        <%= render "form", post:@post %>

        <br>

            <div>
                <%= link_to "Back to posts", posts_path%>
            </div>
    </div>
<%end%>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag :modal do %>
    <%= render @post %>
<% end %>
<div>

    <%= link_to "Back to posts", posts_path %>

    <%= button_to "Destroy this post", @post, method: :delete %>
</div>